### PR TITLE
Renamed schema testfiles to match modules

### LINKED ISSUE #69: Rename schema test files to match modules
When we were renaming schema version files to match the `vXX_XX.py` pattern, we forgot to rename their test files along with them. Rename the `test_v*.py` files in the `kcidb_io/schema` directory to match the names of modules they're testing.

### PR DESCRIPTION
**Pull request by Aman-Jamshed**
fixes #69

### CODE REVIEW

**Comment by spbnick** [comment]
Thanks a lot, Aman! Merging!
Don't hesitate to look at our "[good second issues](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+no%3Aassignee+repo%3Akernelci%2Fkcidb-io+repo%3Akernelci%2Fkcidb+label%3A%22good+second+issue%22+)" and pick something else. Those could be difficult, and you could also wait until tomorrow, when I'll try to post some more "[good first issues](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+no%3Aassignee+repo%3Akernelci%2Fkcidb-io+repo%3Akernelci%2Fkcidb+label%3A%22good+first+issue%22)"

**Comment by Aman-Jamshed** [comment]
Thanks @spbnick 
Yes, please post some more good first issues.
I want to understand how things are working on kcidb can you please guide me a lil bit?

**Comment by spbnick** [comment]
Will try to post more issues today.

Meanwhile try watching one of my (somewhat old) presentations on KCIDB: https://resources.linaro.org/en/resource/U4us6hWZWU8irp9gdRBXz4

You can also glean some more details from the documentation written so far: https://kernelci.org/docs/kcidb/

**Comment by Aman-Jamshed** [comment]
That’s so kind of you. @spbnick 
Okay, I'll check both.  :)

**Pull request merged**
