### PR TITLE
Remove functions in kcidb io.schema

### PR DESCRIPTION
**Pull request by NikkyXO**
Remove all functions in kcidb_io.schema to reduce confusion

### CODE REVIEW

**Comment by spbnick** [comment]
Looks like you're including a change that's already merged (removing functions from the `kcidb_io/__init__.py`), in addition to the one you're trying to do.  You need to fetch fresh changes from the upstream repository, and rebase your changes on top of that.

**Comment by NikkyXO** [comment]
> Looks like you're including a change that's already merged (removing functions from the `kcidb_io/__init__.py`), in addition to the one you're trying to do. You need to fetch fresh changes from the upstream repository, and rebase your changes on top of that.

thanks, i just did that, is this recent changes okay now

**Comment by spbnick** [comment]
Your PR still tries to remove functions from *both* files.

**Comment by NikkyXO** [comment]
> Your PR still tries to remove functions from _both_ files.

@spbnick  adjusted it

**Comment by spbnick** [comment]
Thank you, @NikkyXO! This looks good in principle, but please fix the things CI is complaining about.

**Comment by spbnick** [comment]
Don't mind the `trigger_kcidb_testing` failing, though. This is due to your lack of access to our deployments.

**Comment by NikkyXO** [comment]
> Thank you, @NikkyXO! This looks good in principle, but please fix the things CI is complaining about.

already fixed, except for the last

**Comment by spbnick** [comment]
Perfect! Thank you, @NikkyXO :relaxed: Merging!

**Pull request merged**
