### PR TITLE
Feat/remove all functions from kcidb io.schema

### PR DESCRIPTION
**Pull request by NikkyXO**
Functions calling _warn_deprecation in schema/__init__.py removed

### CODE REVIEW

**Comment by spbnick** [comment]
Looks perfect, thank you @NikkyXO :relaxed: Please don't mind the `trigger_kcidb_testing` CI check failing. We still gotta work on it, GitHub permissions are tricky.

However, could you please squash your commits into one, following the commit guidelines I just posted in https://github.com/kernelci/kcidb/pull/380 ? Would also appreciate feedback on that one, if anything is unclear/missing/wrong.

**Comment by NikkyXO** [comment]
> Looks perfect, thank you @NikkyXO relaxed Please don't mind the `trigger_kcidb_testing` CI check failing. We still gotta work on it, GitHub permissions are tricky.
> 
> However, could you please squash your commits into one, following the commit guidelines I just posted in [kernelci/kcidb#380](https://github.com/kernelci/kcidb/pull/380) ? Would also appreciate feedback on that one, if anything is unclear/missing/wrong.

@spbnick thank you, i have squashed the commits into one

**Comment by spbnick** [comment]
Thank you, @NikkyXO. Could you also amend the commit message according to the guidelines (use imperative mood), and remove the unnecessary details of what you did from the message? Something like just "Remove deprecated functions from kcidb_io module" would do. Thanks!

**Comment by NikkyXO** [comment]
commit message has been ammended

**Comment by spbnick** [comment]
Thanks a lot, @NikkyXO, merging!

Nitpick: the commit subject could still use an improvement by switching to imperative mood (writing "Remove", not "Removed"), but just a few commits like that is no matter.

Congrats on your first merge in KCIDB project :partying_face: Feel free to pick another issue. We have more unassigned [good first issues](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+no%3Aassignee+repo%3Akernelci%2Fkcidb-io+repo%3Akernelci%2Fkcidb+label%3A%22good+first+issue%22), or, if you're up to it, some [good second issues](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+no%3Aassignee+repo%3Akernelci%2Fkcidb-io+repo%3Akernelci%2Fkcidb+label%3A"good+second+issue"), which would be a bit harder.

**Pull request merged**
